export const sidemenu_items = [
    {
        id:"1",
        name:"Nickname",
        childs:[
            {
                name:"Halter",
            },
            {
                name:"Wrap",
            },
            {
                name:"Chemise",
            },
            {
                name:"Slip",
            },
            {
                name:"Jumper",
            },
        ]
    },
    {
        id:"2",
        name:"Silhouette",
        childs:[
            {
                name:"Symmetrical",
            },
            {
                name:"Asymmetrical",
            },
            {
                name:"Peplum",
            },
            {
                name:"Circle",
            },
            {
                name:"Pencil",
            },
        ]
    },
    {
        id:"3",
        name:"Waistline",
        childs:[
            {
                name:"Empire",
            },
            {
                name:"High",
            },
            {
                name:"Normal",
            },
            {
                name:"Basque",
            },
            {
                name:"no-waistline",
            },
        ]
    },
    {
        id:"4",
        name:"Length",
        childs:[
            {
                name:"above-the-knee",
            },
            {
                name:"knee",
            },
            {
                name:"below-the-knee",
            },
            {
                name:"floor",
            },
            {
                name:"sleeveless",
            },
            {
                name:"wrist-length",
            },
        ]
    },
    {
        id:"5",
        name:"Collar",
        childs:[
            {
                name:"regular",
            },
            {
                name:"asymmetric",
            },
            {
                name:"v-neck",
            },
            {
                name:"round-neck",
            },
            {
                name:"neckless",
            },
        ]
    }
]    
